name: Botgram shell-bot Runner

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

env:
  GitHubMail: "adameyyad999@gmail.com"
  GitHubName: "nnippon"
  # GH_TOKEN >> Github Personal Access Token << In Repository Secrets
  # authToken >> Telegram Bot Token << In Repository Secrets
  # ownerID >> Telegram User/Admin owner ID << In Repository Secrets

jobs:
  shellbot:
    runs-on: ubuntu-latest

    steps:
     - name: Checkouts
       uses: actions/checkout@master
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
     - uses: rokibhasansagar/slimhub_actions@main

     - name: Set Git Configs & Secrets
       run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

     - name: Re-install nodejs and npm
       run: |
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get -qq -y install nodejs rclone

     - name: tmate configs
       run: |
          sudo apt update
          sudo ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""
          sudo apt install tmate

     - name: utils
       run: |
          sudo apt install megatools
          cd /home/runner && curl -sL https://git.io/file-transfer | sh
  
     - name: Setup Rclone
       run: |
             git clone https://github.com/nnippon/rclone
             mkdir -p /home/runner/.config/rclone
             mv rclone/rclone.conf /home/runner/.config/rclone
             rm -rf rclone
             mkdir /home/runner/drive
             rclone mount --daemon gdrive:/ /home/runner/drive

     - name: Install ErfanGSIs Requirements
       run: |
          git clone --recurse-submodules http://github.com/nnippon/gsitools /home/runner/ErfanGSIs
          bash /home/runner/ErfanGSIs/setup.sh

     - name: Clone botgram shell-bot repo and Generate config
       run: |
          git clone https://github.com/nnippon/shell-bot --depth=1 shell-bot
          cd shell-bot
          cat << EOF > config.json
          {
            "authToken": "${{ secrets.authToken }}",
            "owner": ${{ secrets.ownerID }}
          }
          EOF

     - name: Install nodejs Dependencies
       run: |
          cd shell-bot
          npm install

     - name: Run shell-bot server
       timeout-minutes: 320
       continue-on-error: true
       run: |
          cd shell-bot
          export PATH="/home/runner:$PATH"
          node server

     - name: Workflow Looping
       run: |
          git clone https://github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Looping at $(date -u +%D-%T%P)"
          git push -q https://github.com/${GITHUB_REPOSITORY} HEAD:main
